language: node_js
sudo: required
node_js:
  - "0.10"
  - "4"
  - "4.4.3"
  - "6"
  - "8"
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install --assume-yes apache2-utils
  - npm install -g npm@2.13.5
  - npm config set strict-ssl false
install: npm install
env:
  - MONGODB_VERSION=2.4
  - MONGODB_VERSION=3.2
script:
  - npm test
matrix:
  include:
  # Include sync acceptance tests for node 4
  - node_js: "4.4.3"
    services:
    - docker
    script:
      - npm link
      - git clone https://github.com/feedhenry/sync-acceptance-testing.git
      - cd sync-acceptance-testing
      - npm install
      - npm link fh-mbaas-api
      - npm test
      